### ISSUE TITLE
MSO1074Z Compatibility

### ISSUE THREAD

**Issue by Gajdascz** [bveina/Rigol-Scope-Snap#2]
RIGOL TECHNOLOGIES,MSO1074Z,DS1ZC210200064,00.04.04.SP4

[MSO|DS]1[0-9][0-9][0-9][ZB]

**Comment by bveina** [comment]
yep, it looks like enabling the logic analyzer on an DS1074Z turns the model into an MSO1074Z.
changing the regex from DS1[0-9][0-9][0-9][ZB] to recognize [MSO|DS] will treat the MSO1074Z just like an DS1074. are there any other differences that would warrant a different Model entry in the instrument list file?

**Comment by bveina** [comment]
this was fixed in 8a68778d98b5ca61eb738192bb565f9249f852f1 and included in version 1.7
