### ISSUE TITLE
network address argument

### ISSUE THREAD

**Issue by jerome-la** [bveina/Rigol-Scope-Snap#3]
Would it be possible to add an optional command line parameter to specify the network address
ScopeSnapSharp.exe    TCPIP::192.168.0.100::INSTR

to make it easier to start in a batch file
thanks

**Comment by bveina** [comment]
command line arguments are an option for future development. but not planed for any release this year. ill see if there is a quick fix.

At the moment the only way to connect to a TCPIP resource is to double click on the grayed out text box then type in the Resource string. i havent invested a lot of time into discovering why the NI drivers cant auto discover network resources. if anyone has ideas or wants to submit a PR that would be great

**Comment by bveina** [comment]
... wait what? apparently i added this feature in e97c167c6f7a67c643c47ea048d7acb0df026e40 shortly after the release of 1.6
you should just be able to run "Scopesnap.exe TCPIP::192.168.0.100::INSTR" this should be live in version 1.7. please test and open up new issue if it doesnt work as expected.
